# Generated by Django 5.2.15 on 2026-07-09 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_darajathreshold_norm_normband_norm_uniq_norm_version'),
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comparator', models.CharField(choices=[('lte', '≤'), ('lt', '<'), ('gte', '≥'), ('gt', '>')], max_length=3)),
                ('threshold', models.PositiveSmallIntegerField()),
                ('template_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.exercise')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='scoring.evaluation')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='recommendations.recommendationrule')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
