# Generated by Django 5.2.15 on 2026-07-07 14:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
        ('catalog', '0002_darajathreshold_norm_normband_norm_uniq_norm_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('source', models.CharField(choices=[('manual', "Qo'lda"), ('excel', 'Excel')], default='manual', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('finalized', 'Yakunlangan')], default='draft', max_length=10)),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=6)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('age_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.agecategory')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='athletes.athlete')),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entered_sessions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.organization')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.region')),
                ('sport_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.sporttype')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='measurements.testsession')),
            ],
            options={
                'ordering': ['session', 'exercise'],
                'constraints': [models.UniqueConstraint(fields=('session', 'exercise'), name='uniq_measurement_per_exercise')],
            },
        ),
    ]
