# Generated by Django 5.2.15 on 2026-07-08 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
        ('catalog', '0002_darajathreshold_norm_normband_norm_uniq_norm_version'),
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=6)),
                ('session_date', models.DateField()),
                ('physical_total', models.PositiveSmallIntegerField()),
                ('daraja', models.CharField(choices=[('I', 'I daraja'), ('II', 'II daraja'), ('III', 'III daraja'), ('none', 'Nishonsiz')], max_length=4)),
                ('color', models.CharField(choices=[('green', 'Yashil'), ('yellow', 'Sariq'), ('red', 'Qizil')], max_length=6)),
                ('ranking_score', models.PositiveSmallIntegerField()),
                ('computed_at', models.DateTimeField()),
                ('age_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.agecategory')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='athletes.athlete')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.region')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='measurements.testsession')),
                ('sport_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.sporttype')),
            ],
            options={
                'ordering': ['-session_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('points', models.PositiveSmallIntegerField()),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='scoring.evaluation')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.exercise')),
            ],
            options={
                'ordering': ['evaluation', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['region', 'sport_type', 'age_category', 'gender', 'ranking_score'], name='eval_ranking_idx'),
        ),
        migrations.AddConstraint(
            model_name='indicatorscore',
            constraint=models.UniqueConstraint(fields=('evaluation', 'exercise'), name='uniq_indicator_per_exercise'),
        ),
    ]
