# Generated by Django 5.2.15 on 2026-07-07 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordinal', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('age_min', models.PositiveSmallIntegerField()),
                ('age_max', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'age category',
                'verbose_name_plural': 'age categories',
                'ordering': ['ordinal'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['region', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('unit', models.CharField(max_length=20)),
                ('value_type', models.CharField(choices=[('seconds', 'Soniya'), ('minsec', 'Daqiqa:soniya'), ('count', 'Son'), ('cm_signed', 'Santimetr (ishorali)')], max_length=10)),
                ('direction', models.CharField(choices=[('higher', "Ko'proq — yaxshiroq"), ('lower_is_better', 'Kamroq — yaxshiroq')], max_length=15)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('OTM', 'OTM'), ('OPSTTM', 'OPSTTM')], max_length=10)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='catalog.district')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='catalog.region')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='catalog.region'),
        ),
        migrations.CreateModel(
            name='TestBattery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=6)),
                ('is_active', models.BooleanField(default=True)),
                ('age_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batteries', to='catalog.agecategory')),
            ],
            options={
                'verbose_name': 'test battery',
                'verbose_name_plural': 'test batteries',
                'ordering': ['age_category', 'gender'],
            },
        ),
        migrations.CreateModel(
            name='BatteryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='battery_items', to='catalog.exercise')),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.testbattery')),
            ],
            options={
                'ordering': ['battery', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(fields=('region', 'name'), name='uniq_district_per_region'),
        ),
        migrations.AddConstraint(
            model_name='testbattery',
            constraint=models.UniqueConstraint(fields=('age_category', 'gender'), name='uniq_battery_per_group'),
        ),
        migrations.AddConstraint(
            model_name='batteryitem',
            constraint=models.UniqueConstraint(fields=('battery', 'order'), name='uniq_item_order_per_battery'),
        ),
        migrations.AddConstraint(
            model_name='batteryitem',
            constraint=models.UniqueConstraint(fields=('battery', 'exercise'), name='uniq_exercise_per_battery'),
        ),
    ]
