# Generated by Django 5.2.15 on 2026-07-07 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DarajaThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('I', 'I daraja'), ('II', 'II daraja'), ('III', 'III daraja')], max_length=3, unique=True)),
                ('total_min', models.PositiveSmallIntegerField()),
                ('total_max', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['-total_min'],
            },
        ),
        migrations.CreateModel(
            name='Norm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age_min', models.PositiveSmallIntegerField()),
                ('age_max', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=6)),
                ('valid_from', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='norms', to='catalog.exercise')),
            ],
            options={
                'ordering': ['exercise', 'gender', 'age_min', '-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='NormBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points', models.PositiveSmallIntegerField()),
                ('lower_bound', models.DecimalField(decimal_places=2, max_digits=8)),
                ('upper_bound', models.DecimalField(decimal_places=2, max_digits=8)),
                ('norm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='catalog.norm')),
            ],
            options={
                'ordering': ['norm', '-points'],
            },
        ),
        migrations.AddConstraint(
            model_name='norm',
            constraint=models.UniqueConstraint(fields=('exercise', 'age_min', 'age_max', 'gender', 'valid_from'), name='uniq_norm_version'),
        ),
    ]
