# Generated by Django 5.2.15 on 2026-07-07 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_darajathreshold_norm_normband_norm_uniq_norm_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('birth_year', models.PositiveSmallIntegerField(db_index=True)),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=6)),
                ('razryad', models.CharField(blank=True, max_length=50)),
                ('training_experience', models.CharField(blank=True, max_length=100)),
                ('main_competitions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('coach', models.ForeignKey(blank=True, limit_choices_to={'role': 'coach'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='athletes', to='catalog.district')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='athletes', to='catalog.organization')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='athletes', to='catalog.region')),
                ('sport_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='athletes', to='catalog.sporttype')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
