# Generated by Django 5.2.15 on 2026-07-10 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_initial_assignments(apps, schema_editor):
    """Open one current (valid_to=None) record per existing athlete, so the one-open invariant
    holds for pre-existing rows and future transfers have a record to close."""
    Athlete = apps.get_model("athletes", "Athlete")
    History = apps.get_model("athletes", "AthleteAssignmentHistory")
    History.objects.bulk_create(
        History(
            athlete_id=a.id,
            region_id=a.region_id,
            district_id=a.district_id,
            organization_id=a.organization_id,
            sport_type_id=a.sport_type_id,
            coach_id=a.coach_id,
            changed_by_id=None,
            valid_from=a.created_at.date(),
            valid_to=None,
            reason="Initial",
        )
        for a in Athlete.objects.all()
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
        ('catalog', '0002_darajathreshold_norm_normband_norm_uniq_norm_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='athletes.athlete')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(blank=True, limit_choices_to={'role': 'coach'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.district')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.organization')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.region')),
                ('sport_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.sporttype')),
            ],
            options={
                'ordering': ['-valid_from', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('valid_to__isnull', True)), fields=('athlete',), name='uniq_open_assignment_per_athlete')],
            },
        ),
        migrations.RunPython(backfill_initial_assignments, noop),
    ]
