# Generated by Django 5.2.15 on 2026-07-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super admin'), ('region_admin', 'Viloyat admin'), ('coach', 'Murabbiy'), ('lab_operator', 'Laboratoriya operatori'), ('ministry', 'Vazirlik vakili')], default='lab_operator', max_length=20),
        ),
    ]
