# Generated by Django 5.2.15 on 2026-07-09 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('athlete', 'Sportchi'), ('region', 'Viloyat'), ('sport', 'Sport turi'), ('republic', 'Respublika')], max_length=10)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word'), ('excel', 'Excel')], max_length=5)),
                ('params', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Navbatda'), ('processing', 'Ishlanmoqda'), ('done', 'Tayyor'), ('failed', 'Xato')], default='pending', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('error', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
